-- CREATE DATABASE classicmodels;

USE classicmodels;

-- Change datatype to Date
-- ALTER TABLE orders MODIFY orderDate DATE; 
-- ALTER TABLE orders MODIFY requiredDate DATE;
-- ALTER TABLE orders MODIFY shippedDate DATE;
-- ALTER TABLE payments MODIFY paymentDate DATE;

-- Add column revenue in order_details and fill values
-- ALTER TABLE order_details ADD COLUMN revenue DECIMAL(10,2);
-- UPDATE order_details SET revenue=(quantityOrdered * priceEach);



-- A) BEGINNER LEVEL 

-- 1) Display all records from customers table
-- SELECT * FROM customers;

-- 2) Find all customers from the USA.
-- SELECT * FROM customers
-- WHERE country='USA';

-- 3) Display all employees with their first name and last name.
-- SELECT firstName, lastName FROM employees;

-- 4) Find all products with a buy price greater than 50.
-- SELECT productName, buyPrice FROM products
-- WHERE buyPrice>50;

-- 5) Display all orders with status "Shipped".
-- SELECT * FROM orders
-- WHERE status='shipped';

-- 6) Find the total number of customers.
-- SELECT COUNT(*) AS total_number_of_cutomers FROM customers;

-- 7) Find the total number of employees.
-- SELECT COUNT(*) AS total_number_of_employees FROM employees;

-- 8) Find the total number of products.
-- SELECT COUNT(*) AS total_number_of_products FROM products;

-- 9) Find the highest product price.
-- SELECT productName, MAX(MSRP) AS highest_price FROM products
-- GROUP BY productName order by highest_price DESC LIMIT 1;

-- 10) Find the lowest product price.
-- SELECT productName, MAX(MSRP) AS lowest_price FROM products
-- GROUP BY productName order by lowest_price LIMIT 1;

-- 11) Find the average product buy price.
-- SELECT AVG(buyPrice) AS AVG_of_buy_price FROM products;

-- 12) Find the total payment amount received.
-- SELECT SUM(amount) AS total_amount FROM payments;

-- 13) Find all unique countries from the customers table.
-- SELECT DISTINCT country FROM customers;

-- 14) Display all product lines available.
-- SELECT DISTINCT productLine FROM products;

-- 15) Find customers whose credit limit is greater than 100000.
-- SELECT customerName, creditLimit FROM customers
-- WHERE creditLimit>100000;

-- 16) Find orders placed after January 1, 2004.
-- SELECT * FROM orders
-- WHERE orderDate > '2004-01-01';

-- 17) Sort products by buy price from highest to lowest.
-- SELECT * FROM products
-- ORDER BY buyPrice DESC;

-- 18) Display customers alphabetically by customer name.
-- SELECT * FROM customers
-- ORDER BY customerName;

-- 19) Find the total quantity of products ordered.
-- SELECT SUM(quantityOrdered) AS 'total quantity of ordered product' FROM order_details;

-- 20) Count the number of orders based on order status.
-- SELECT status, COUNT(*) AS 'count' FROM orders
-- GROUP BY status;



-- B) INTERMEDIATE LEVEL

-- 1) Find the number of customers in each country.
-- SELECT country, COUNT(*) AS count FROM customers
-- GROUP BY country ORDER BY count DESC;

-- 2) Find the average credit limit for each country.
-- SELECT country, AVG(creditLimit) AS 'AVG of Credit Limit' FROM customers
-- GROUP BY country ORDER BY AVG(creditLimit) DESC;

-- 3) Find total sales revenue from order details.
-- SELECT SUM(revenue) AS total_sales_revenue FROM order_details;

-- 4) Find total sales revenue generated by each product.
-- SELECT p.productName, SUM(o.revenue) AS total_revenue FROM products p
-- INNER JOIN order_details o ON p.productCode=o.productCode
-- GROUP BY p.productName 
-- ORDER BY total_revenue DESC;

-- 5) Find the top 10 selling products by quantity.
-- SELECT p.productName, SUM(o.quantityOrdered) AS total_quantity FROM products p
-- INNER JOIN order_details o ON p.productCode=o.productCode
-- GROUP BY p.productName
-- ORDER BY total_quantity DESC LIMIT 10;

-- 6) Find total orders placed by each customer.
-- SELECT c.customerName, COUNT(o.orderNUmber) AS total_orders FROM customers c
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- GROUP BY c.customerName
-- ORDER BY total_orders DESC;

-- 7) Display customer names with their order numbers.
-- SELECT c.customerName, o.orderNumber FROM customers c
-- INNER JOIN orders o ON o.customerNumber=c.customerNumber
-- ORDER BY o.orderNumber;

-- 8) Display product names with their order quantities.
-- SELECT p.productName, sum(o.quantityOrdered) AS total_of_order_quantity FROM products p
-- RIGHT JOIN order_details o ON p.productCode=o.productCode
-- GROUP BY p.productName
-- ORDER BY total_of_order_quantity DESC;

-- 9) Find total revenue generated by each customer.
-- SELECT c.customerName, SUM(od.revenue) AS total_revenue FROM customers c
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY c.customerName
-- ORDER BY total_revenue DESC;

-- 10) Find total payments received from each customer.
-- SELECT c.customerName, SUM(p.amount) AS total_payments FROM customers c
-- LEFT JOIN payments p ON c.customerNumber=p.customerNumber
-- GROUP BY c.customerName
-- ORDER BY total_payments DESC;

-- 11) Find employees and the number of customers assigned to them.
-- SELECT CONCAT(e.firstName,' ',e.lastName) AS employeeName, COUNT(*) AS total_customer FROM customers c
-- INNER JOIN employees e ON c.salesRepEmployeeNumber=e.employeeNumber
-- GROUP BY e.firstName, e.lastName
-- ORDER BY total_customer DESC;

-- 12) Find the number of employees working in each office.
-- SELECT o.officeCode, o.city, COUNT(e.employeeNumber) AS total_employee FROM offices o
-- LEFT JOIN employees e ON e.officeCode=o.officeCode
-- GROUP BY o.officeCode, o.city;

-- 13) Find total sales revenue generated from customers in each country.
-- SELECT c.country, SUM(od.revenue) AS total_revenue FROM customers c
-- LEFT JOIN orders o ON o.customerNumber=c.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY c.country
-- ORDER BY total_revenue DESC;

-- 14) Find monthly sales revenue.
-- SELECT MONTHNAME(o.orderDate) AS month, SUM(od.revenue) AS total_revenue FROM orders o
-- LEFT JOIN order_Details od ON o.orderNumber=od.orderNumber
-- GROUP BY month;

-- 15) Find products whose total sales quantity is greater than 900.
-- SELECT p.productName, SUM(o.quantityOrdered) AS total_sales_quantity FROM products p
-- LEFT JOIN order_details o ON o.productCode=p.productCode
-- GROUP BY p.productName
-- HAVING total_sales_quantity > 900
-- ORDER BY total_sales_quantity DESC;

-- 16) Find countries having more than 10 customers.
-- SELECT country, COUNT(*) AS total_customers  FROM customers
-- GROUP BY country
-- HAVING total_customers > 10
-- ORDER BY total_customers;

-- 17) Find customers who have placed more than 5 orders.
-- SELECT c.customerName, COUNT(*) AS total_orders FROM customers c
-- LEFT JOIN orders o ON o.customerNumber=c.customerNumber
-- GROUP BY c.customerName
-- HAVING total_orders>5;

-- 18) Find the employee who handles the highest number of customers.
-- SELECT CONCAT(e.firstName,' ',e.lastName) AS employeeName, COUNT(*) AS total_customers FROM employees e
-- LEFT JOIN customers c ON e.employeeNumber=c.salesRepEmployeeNumber
-- GROUP BY employeeName
-- ORDER BY total_customers DESC;

-- 19) Display order details with customer name and product name.
-- SELECT  c.customerName, p.productName, od.* FROM orders o
-- INNER JOIN customers c ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON od.orderNumber=o.orderNumber
-- INNER JOIN products p ON p.productCode=od.productCode;

-- 20) Find the best-selling product in product line.
-- SELECT p.productLine, p.productName, SUM(od.revenue) AS total_sales FROM products p
-- JOIN order_details od ON p.productCode=od.productCode
-- GROUP BY p.productLine, p.productName
-- ORDER BY total_sales;



-- C) ADVANCED LEVEL

-- 1) Find the top 5 customers based on total spending.
-- SELECT c.customerNumber, c.customerName, SUM(od.revenue) AS total_spending FROM customers c
-- LEFT JOIN orders o ON o.customerNumber=c.customerNumber
-- INNER JOIN order_details od ON od.orderNumber=o.orderNumber
-- GROUP BY c.customerNumber, c.customerName
-- ORDER BY total_spending DESC LIMIT 5;

-- 2) Rank products based on total revenue.
-- SELECT p.productCode, p.productName, SUM(od.revenue) AS total_revenue FROM products p
-- INNER JOIN order_details od ON p.productCode=od.productCode
-- GROUP BY p.productCode, p.productName
-- ORDER BY total_revenue DESC;

-- 3) Find the second highest selling product.
-- SELECT p.productCode, p.productName, SUM(od.quantityOrdered) AS total_sale_by_quantity FROM products p
-- INNER JOIN order_details od ON p.productCode=od.productCode
-- GROUP BY p.productCode, p.productName
-- ORDER BY total_sale_by_quantity DESC
-- LIMIT 1 OFFSET 1;

-- 4) Find the second highest paying customer.
-- SELECT c.customerNumber, c.customerName, SUM(od.revenue) AS total_pay FROM customers c
-- LEFT JOIN orders o ON o.customerNumber=c.customerNumber
-- INNER JOIN order_details od ON od.orderNumber=o.orderNumber
-- GROUP BY c.customerNumber, c.customerName
-- ORDER BY total_pay DESC
-- LIMIT 1 OFFSET 1;

-- 5) Calculate each country's contribution percentage to total sales.
-- SELECT c.city, SUM(od.revenue) AS total_sales, 
-- ROUND((SUM(od.revenue) / (SELECT SUM(revenue) FROM order_details)) * 100,2) AS contribute_percentage
-- FROM customers c
-- LEFT JOIN orders o ON o.customerNumber=c.customerNumber
-- INNER JOIN order_details od ON od.orderNumber=o.orderNumber
-- GROUP BY c.city
-- ORDER BY total_sales DESC;

-- 6) Find average monthly sales revenue.
-- SELECT AVG(monthly_revenue) AS avg_monthly_sales_revenue FROM
-- (
--     SELECT MONTH(o.orderDate) AS month, SUM(od.revenue) AS monthly_revenue
--     FROM orders o
--     JOIN order_details od ON o.orderNumber=od.orderNumber
--     GROUP BY MONTH(o.orderDate)
-- ) AS sales_revenue;

-- 7) Find yearly sales revenue.
-- SELECT AVG(yearly_revenue) AS avg_yearly_sales_revenue FROM 
-- (
-- 	SELECT YEAR(o.orderDate) AS year, SUM(od.revenue) AS yearly_revenue 
--     FROM orders o
--     INNER JOIN order_details od ON od.orderNumber=o.orderNumber
--     GROUP BY year
-- ) AS sales_revenue;

-- 8) Find customers who have never placed an order.
-- SELECT c.customerNumber, c.customerName FROM customers c
-- LEFT JOIN orders o ON c.customerNumber=o.customerNumber
-- WHERE o.orderNumber IS NULL;

-- 9) Find products that have never been ordered.
-- SELECT p.productCode, p.productName FROM products p
-- LEFT JOIN order_details od ON p.productCode=od.productCode
-- WHERE od.orderNumber IS NULL;

-- 10) Find employees who report to the same manager.
-- SELECT reportsTo, COUNT(employeeNumber) AS total_employees FROM employees
-- WHERE reportsTo IS NOT NULL
-- GROUP BY reportsTo
-- HAVING total_employees > 1;

-- 11) Create a view showing customer sales performance.
-- CREATE VIEW customer_sales_performance AS
-- SELECT c.customerNumber, c.customerName, SUM(od.revenue) AS total_sales FROM customers c
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY c.customerNumber, c.customerName
-- ORDER BY total_sales DESC;
-- SELECT * FROM customer_sales_performance;

-- 12) Create a view showing product sales analysis.
-- CREATE VIEW product_sales_analysis AS
-- SELECT p.productCode, p.productName, SUM(od.quantityOrdered) AS total_quantity, SUM(od.revenue) AS total_revenue
-- FROM products p
-- INNER JOIN order_details od ON p.productCode=od.productCode
-- GROUP BY p.productCode, p.productName;
-- SELECT * FROM product_sales_analysis

-- 13) Create a stored procedure to get customer order history using customerNumber.
-- DELIMITER $$
-- CREATE PROCEDURE CustomerOrderHistory(IN p_customerNumber INT)
-- BEGIN
--     SELECT o.orderNumber, o.orderDate, o.status FROM orders o
--     WHERE o.customerNumber = p_customerNumber;
-- END $$
-- DELIMITER ;
-- CALL CustomerOrderHistory(103);

-- 14) Create a stored procedure to calculate total sales for a given product.
-- DELIMITER $$
-- CREATE PROCEDURE ProductTotalSales(IN p_productCode VARCHAR(20))
-- BEGIN
--     SELECT p.productName, SUM(od.revenue) AS total_sales FROM products p
--     INNER JOIN order_details od ON p.productCode=od.productCode
--     GROUP BY p.productName;
-- END $$
-- DELIMITER ;
-- CALL ProductTotalSales('S10_1678');

-- 15) Find the employee with the highest sales revenue.
-- SELECT e.employeeNumber, CONCAT(e.firstName,' ',e.lastName) AS employeeName, SUM(od.revenue) AS total_sales 
-- FROM employees e
-- INNER JOIN customers c ON e.employeeNumber=c.salesRepEmployeeNumber
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY e.employeeNumber, employeeName
-- ORDER BY total_sales DESC
-- LIMIT 1;

-- 16) Find the most profitable products based on MSRP and buy price.
-- SELECT productCode, productName, buyPrice, MSRP, (MSRP - buyPrice) AS profit
-- FROM products
-- ORDER BY profit DESC;

-- 17) Find customers whose spending is above the average customer spending.
-- SELECT c.customerNumber, c.customerName, SUM(od.revenue) AS total_spending
-- FROM customers c
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY c.customerNumber, c.customerName
-- HAVING total_spending >
-- (
--     SELECT AVG(total_spending) FROM 
--     (
--         SELECT SUM(revenue) AS total_spending FROM orders o
--         INNER JOIN order_details od ON o.orderNumber=od.orderNumber
--         GROUP BY o.customerNumber
--     ) AS avg_table
-- );

-- 18) Find products whose revenue is higher than the average product revenue.
-- SELECT p.productCode, p.productName, SUM(od.revenue) AS total_revenue
-- FROM products p
-- INNER JOIN order_details od ON p.productCode=od.productCode
-- GROUP BY p.productCode, p.productName
-- HAVING total_revenue >
-- (
--     SELECT AVG(product_revenue) FROM
--     (
--         SELECT SUM(revenue) AS product_revenue FROM order_details
--         GROUP BY productCode
--     ) AS avg_table
-- );

-- 19) Create a complete sales report using multiple table joins.
-- SELECT o.orderNumber, o.orderDate, c.customerName, p.productName, od.quantityOrdered, od.priceEach, od.revenue
-- FROM orders o
-- INNER JOIN customers c ON o.customerNumber=c.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- INNER JOIN products p ON od.productCode=p.productCode;

-- 20) Create a final SQL query:
-- a) Total Revenue
-- SELECT SUM(revenue) AS total_revenue FROM order_details;

-- b) Total Orders
-- SELECT COUNT(*) AS total_orders FROM orders;

-- c) Total Customers
-- SELECT COUNT(*) AS total_customers FROM customers;

-- d) Top 10 Products
-- SELECT p.productName, SUM(od.revenue) AS Total_Revenue FROM products p
-- INNER JOIN order_details od ON p.productCode = od.productCode
-- GROUP BY p.productName
-- ORDER BY Total_Revenue DESC
-- LIMIT 10;

-- e) Monthly Sales Trend
-- SELECT YEAR(o.orderDate) AS year, MONTHNAME(o.orderDate) AS month, SUM(od.revenue) AS total_revenue
-- FROM orders o
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY year, month
-- ORDER BY year, month

-- f) Country-wise Sales
-- SELECT c.country, SUM(od.revenue) AS Total_Revenue FROM customers c
-- INNER JOIN orders o ON c.customerNumber=o.customerNumber
-- INNER JOIN order_details od ON o.orderNumber=od.orderNumber
-- GROUP BY c.country
-- ORDER BY Total_Revenue DESC;
